[release-4.5] Bug 1881957: updating EO to adopt an existing cluster if cr nodes uuid is nil
openshift/elasticsearch-operator pull request #495
Opened 2020-09-23 21:15 UTC by ewolinetz

To address https://bugzilla.redhat.com/show_bug.cgi?id=1881957
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/471

This addresses cases where there is or was an existing cluster created (deployments, pods, pvcs, etc) who's cluster name is the same as the CR name, however the new elasticsearch CR is missing UUIDs.

As part of the recovery/adoption process, it will be required that the PVCs to be picked back up have the label logging-cluster: <name-of-the-cr>. It will also be validated against the name of the cluster that the PVC name is based on.

Recovery/adoption will be triggered upon the processing of a CR that is missing UUIDs. It will only try to recover UUIDs for nodes that do not already have UUIDs defined.

Further documentation will need to be developed and publish as part of how to recover data that from another PVC. This PR does not seek to resolve that but rather address cases where an elasticsearch CR may have been removed on accident and then recreated (without UUIDs).

Please note: as part of this change EO will be creating PVCs with the required labels now, so to ensure keeping previously used PVCs they should be labeled per above.

2020-09-24 07:01 UTC, periklis requested changes
Looks good to me in general, however I might be wrong but the merge for `persistentvolumeclaims` blurred some inconsistencies in.

2020-09-24 13:51 UTC, ewolinetz commented on pkg/k8shandler/persistentvolumeclaims.go
> +			current.ObjectMeta.Labels = claim.ObjectMeta.Labels
if nothing is different (that we can change) there isn't a point to making an update call

2020-09-24 13:55 UTC, ewolinetz commented on pkg/k8shandler/persistentvolumeclaims.go
> +	return updatePersistentVolumeClaim(claim, client)
to ensure its correct as we leave this function

2020-09-24 14:43 UTC, ewolinetz commented
/retest

2020-09-24 15:02 UTC, periklis commented
/lgtm

2020-09-25 10:01 UTC, markmc commented
(patch maanger) affecting real-world users

2020-09-25 14:37 UTC, merged

2020-09-28 21:16 UTC, ewolinetz commented
/cherry-pick release-4.4
this was originally reported on 4.4 and likely to still be an issue for customers who haven't upgraded to 4.5 yet