Bug 1884477: Update bundle manifests to reflect latest CRD state
openshift/elasticsearch-operator pull request #509
Opened 2020-10-02 06:53 UTC by periklis

### Description
This PR addresses the sync between our latest CRD state into our bundle manifest directory. This is mandatory to provide an up2date 4.6.0 bundle image.
 
/cc @blockloop 
/assign @ewolinetz 

### Links
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1884477

2020-10-05 13:51 UTC, blockloop approved these changes
/lgtm

2020-10-06 21:47 UTC, ewolinetz requested changes
required in line

2020-10-06 21:47 UTC, ewolinetz commented on bundle.Dockerfile
> -    maintainer="AOS Logging <aos-logging@redhat.com>"
this is required to stay in there... i think i missed a change to our generate. but can you manually add this back in?

2020-10-07 13:54 UTC, ewolinetz approved these changes

2020-10-07 13:55 UTC, ewolinetz commented
this isn't required for 4.6.0 since ART is building bundle images from our `manifest` dir, but it will be required for our post 4.6.z release
/lgtm

2020-10-07 15:43 UTC, ewolinetz commented
/hold
@periklis can you target this at `master-post-release` instead?

2020-10-07 16:35 UTC, periklis commented
> /hold
> @periklis can you target this at `master-post-release` instead?

Why? branch cut happened last friday, thus 4.7 == master.

2020-10-07 17:06 UTC, ewolinetz commented
/hold cancel

2020-10-07 20:11 UTC, merged