Log 2474: Changing prometheus-k8s permissions scope
openshift/elasticsearch-operator pull request #867
Opened 2022-04-11 18:06 UTC by Red-GV

This PR changes the scope of permissions the `prometheus-k8s` ServiceAccount can use by making a `Role`/`RoleBinding` instead of a `ClusterRole`/`ClusterRoleBinding`.

/cc @btaani 
/assign @periklis 

### Links
- JIRA: https://issues.redhat.com/browse/LOG-2474

2022-04-11 19:37 UTC, Red-GV commented
/retest

2022-04-12 07:32 UTC, periklis reviewed
In general looks good to me. Is this PR also targeting any changes for the EO's static manifest in the `config/` directory which get rendered to the `bundle` directory?

2022-04-12 07:32 UTC, periklis commented on internal/elasticsearch/rbac.go
> -	elasticsearchRole := rbac.NewClusterRole(
IIRC this is the only place where we need to create Cluster-scope RBAC resources. If yes, then I suggest to remove also the manifest functions for `NewClusterRole` and `NewClusterRoleBinding`.

2022-04-12 09:37 UTC, btaani commented
/lgtm

2022-04-12 12:25 UTC, Red-GV commented
@periklis Actually, the prometheus rules for the operator under `config` are `Role` / `RoleBinding`. The only one which uses the `ClusterRole` /  `ClusterRoleBinding` is the `metrics-reader`.

2022-04-12 12:37 UTC, periklis requested changes
Please ensure to add a cleanup routine for deleting the old ClusterRole and ClusterRolebinding.

2022-04-12 12:37 UTC, periklis commented
/retest

2022-04-12 15:44 UTC, periklis reviewed
I believe you miss the RBAC for the clusterPermissions in the CSV, right?

2022-04-12 16:02 UTC, Red-GV commented
@periklis I'm not sure if I know the one you are referring to. The csv looks fine to me; not seeing any permissions outside the one for `/metrics` endpoint for this PR.

2022-04-12 16:31 UTC, periklis commented
> @periklis I'm not sure if I know the one you are referring to. The csv looks fine to me; not seeing any permissions outside the one for `/metrics` endpoint for this PR.

By accident your PR works because of: https://github.com/openshift/elasticsearch-operator/blob/master/apis/logging/v1/groupversion_info.go#L30

Usually we need to declare RBAC for the operator to access resources.

2022-04-12 16:31 UTC, periklis commented
/approve

2022-04-12 21:42 UTC, Red-GV commented
I see. Should I tweak that or just leave as is?

2022-04-13 07:11 UTC, periklis commented
/lgtm

2022-04-13 07:14 UTC, merged